apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-synapse-configs
  namespace: wso2-system
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/test/synapse"