apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-execution-plans
  namespace: wso2-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi